### ISSUE TITLE
Install themes

### ISSUE THREAD

**Issue by lenanghai** [zagortenay333/zukitwo-cinnamon#1]
Hey guys, your theme is very awesome, so i can't to apply it to my Linux Mint. Can you please help me or give tutorial to solve it. Thanks you very much !

**Comment by zagortenay333** [comment]
It is written in the instructions. You can install it from within your theme settings. 
Right-click panel --> theme settings

**Comment by lenanghai** [comment]
thanks you for your answer, it's very awesome.
